/*
-- Query: 
-- Date: 2013-10-08 13:37
*/
INSERT INTO `keywords` (`value`) VALUES ('criterios');
INSERT INTO `keywords` (`value`) VALUES ('actas de reunión');
INSERT INTO `keywords` (`value`) VALUES ('estancia');
INSERT INTO `keywords` (`value`) VALUES ('visitante');
INSERT INTO `keywords` (`value`) VALUES ('razones humanitarias');
INSERT INTO `keywords` (`value`) VALUES ('manual');
INSERT INTO `keywords` (`value`) VALUES ('trámites');
INSERT INTO `keywords` (`value`) VALUES ('normatividad interna');
INSERT INTO `keywords` (`value`) VALUES ('requisitos');
INSERT INTO `keywords` (`value`) VALUES ('recursos ejercidos');
INSERT INTO `keywords` (`value`) VALUES ('partida');
INSERT INTO `keywords` (`value`) VALUES ('gasto');
INSERT INTO `keywords` (`value`) VALUES ('productos alimenticios');
INSERT INTO `keywords` (`value`) VALUES ('servicios públicos');
INSERT INTO `keywords` (`value`) VALUES ('delegación regional');
INSERT INTO `keywords` (`value`) VALUES ('presupuesto');
INSERT INTO `keywords` (`value`) VALUES ('atención medica');
INSERT INTO `keywords` (`value`) VALUES ('2006');
INSERT INTO `keywords` (`value`) VALUES ('2007');
INSERT INTO `keywords` (`value`) VALUES ('2008');
INSERT INTO `keywords` (`value`) VALUES ('2009');
INSERT INTO `keywords` (`value`) VALUES ('2010');
INSERT INTO `keywords` (`value`) VALUES ('2011');
INSERT INTO `keywords` (`value`) VALUES ('2012');
INSERT INTO `keywords` (`value`) VALUES ('2004');
INSERT INTO `keywords` (`value`) VALUES ('2005');
INSERT INTO `keywords` (`value`) VALUES ('identificación');
INSERT INTO `keywords` (`value`) VALUES ('funcionarios');
INSERT INTO `keywords` (`value`) VALUES ('agentes públicos');
INSERT INTO `keywords` (`value`) VALUES ('familiares');
INSERT INTO `keywords` (`value`) VALUES ('detención');
INSERT INTO `keywords` (`value`) VALUES ('espacios de dialogo');
INSERT INTO `keywords` (`value`) VALUES ('autoridades públicas');
INSERT INTO `keywords` (`value`) VALUES ('sociedad civil');
INSERT INTO `keywords` (`value`) VALUES ('derechos');
INSERT INTO `keywords` (`value`) VALUES ('niñez migrante');
INSERT INTO `keywords` (`value`) VALUES ('niños');
INSERT INTO `keywords` (`value`) VALUES ('niñas');
INSERT INTO `keywords` (`value`) VALUES ('adolescentes');
INSERT INTO `keywords` (`value`) VALUES ('18 años');
INSERT INTO `keywords` (`value`) VALUES ('asilo');
INSERT INTO `keywords` (`value`) VALUES ('albergues');
INSERT INTO `keywords` (`value`) VALUES ('repatriaciones');
INSERT INTO `keywords` (`value`) VALUES ('expulsiones');
INSERT INTO `keywords` (`value`) VALUES ('devoluciones');
INSERT INTO `keywords` (`value`) VALUES ('reglamentos');
INSERT INTO `keywords` (`value`) VALUES ('circulares');
INSERT INTO `keywords` (`value`) VALUES ('protocolos');
INSERT INTO `keywords` (`value`) VALUES ('ley de migración');
INSERT INTO `keywords` (`value`) VALUES ('convenios');
INSERT INTO `keywords` (`value`) VALUES ('acuerdos');
INSERT INTO `keywords` (`value`) VALUES ('DIF');
INSERT INTO `keywords` (`value`) VALUES ('COMAR');
INSERT INTO `keywords` (`value`) VALUES ('investigaciones');
INSERT INTO `keywords` (`value`) VALUES ('alojamiento');
INSERT INTO `keywords` (`value`) VALUES ('deportación');
INSERT INTO `keywords` (`value`) VALUES ('protocolo de actuación');
INSERT INTO `keywords` (`value`) VALUES ('OPIs');
INSERT INTO `keywords` (`value`) VALUES ('campañas');
INSERT INTO `keywords` (`value`) VALUES ('higiene');
INSERT INTO `keywords` (`value`) VALUES ('salubridad');
INSERT INTO `keywords` (`value`) VALUES ('educación ');
INSERT INTO `keywords` (`value`) VALUES ('operativos');
INSERT INTO `keywords` (`value`) VALUES ('Polícia Federal');
INSERT INTO `keywords` (`value`) VALUES ('seguridad regional');
INSERT INTO `keywords` (`value`) VALUES ('grupos Beta');
INSERT INTO `keywords` (`value`) VALUES ('aseguramiento');
INSERT INTO `keywords` (`value`) VALUES ('plan anual de trabajo');
INSERT INTO `keywords` (`value`) VALUES ('calendarización');
INSERT INTO `keywords` (`value`) VALUES ('capítulo de gasto');
INSERT INTO `keywords` (`value`) VALUES ('Frontera sur');
INSERT INTO `keywords` (`value`) VALUES ('Paisano');
INSERT INTO `keywords` (`value`) VALUES ('Repatriación humana');
INSERT INTO `keywords` (`value`) VALUES ('Rendición de cuentas');
INSERT INTO `keywords` (`value`) VALUES ('PGR');
INSERT INTO `keywords` (`value`) VALUES ('INM');
INSERT INTO `keywords` (`value`) VALUES ('procuración de justicia');
INSERT INTO `keywords` (`value`) VALUES ('delitos contra migrantes');
INSERT INTO `keywords` (`value`) VALUES ('averiguaciones previas');
INSERT INTO `keywords` (`value`) VALUES ('SRE');
INSERT INTO `keywords` (`value`) VALUES ('trabajadores migrantes');
INSERT INTO `keywords` (`value`) VALUES ('revisiones migratorias férreas');
INSERT INTO `keywords` (`value`) VALUES ('lineamientos');
INSERT INTO `keywords` (`value`) VALUES ('control y verificación migratoria');
INSERT INTO `keywords` (`value`) VALUES ('dignificación de estaciones');
INSERT INTO `keywords` (`value`) VALUES ('adquisición de terrenos');
INSERT INTO `keywords` (`value`) VALUES ('construcción');
INSERT INTO `keywords` (`value`) VALUES ('Plan Nacional de Desarrollo');
INSERT INTO `keywords` (`value`) VALUES ('Tenosique');
INSERT INTO `keywords` (`value`) VALUES ('Tabasco');
INSERT INTO `keywords` (`value`) VALUES ('mecanismos');
INSERT INTO `keywords` (`value`) VALUES ('asistencia jurídica');
INSERT INTO `keywords` (`value`) VALUES ('víctimas');
INSERT INTO `keywords` (`value`) VALUES ('custodia');
INSERT INTO `keywords` (`value`) VALUES ('representante consular');
INSERT INTO `keywords` (`value`) VALUES ('sentencias ');
INSERT INTO `keywords` (`value`) VALUES ('Programas');
INSERT INTO `keywords` (`value`) VALUES ('UIFSA');
INSERT INTO `keywords` (`value`) VALUES ('motivos');
INSERT INTO `keywords` (`value`) VALUES ('nacionalidad');
INSERT INTO `keywords` (`value`) VALUES ('condiciones de custodia');
INSERT INTO `keywords` (`value`) VALUES ('medidas de control');
INSERT INTO `keywords` (`value`) VALUES ('incumplimiento');
INSERT INTO `keywords` (`value`) VALUES ('levantamiento');
INSERT INTO `keywords` (`value`) VALUES ('edad');
INSERT INTO `keywords` (`value`) VALUES ('sexo');
INSERT INTO `keywords` (`value`) VALUES ('oficios');
INSERT INTO `keywords` (`value`) VALUES ('autoridades migratorias');
INSERT INTO `keywords` (`value`) VALUES ('trata de personas');
INSERT INTO `keywords` (`value`) VALUES ('repatriadas');
INSERT INTO `keywords` (`value`) VALUES ('regularización');
INSERT INTO `keywords` (`value`) VALUES ('cargos públicos');
INSERT INTO `keywords` (`value`) VALUES ('Estancia Provisional');
INSERT INTO `keywords` (`value`) VALUES ('asilo político');
INSERT INTO `keywords` (`value`) VALUES ('refugiado');
INSERT INTO `keywords` (`value`) VALUES ('denominación legal');
INSERT INTO `keywords` (`value`) VALUES ('salud');
INSERT INTO `keywords` (`value`) VALUES ('aseguramiento');
INSERT INTO `keywords` (`value`) VALUES ('capacitación');
INSERT INTO `keywords` (`value`) VALUES ('acceso a la información');
INSERT INTO `keywords` (`value`) VALUES ('proceso de selección');
INSERT INTO `keywords` (`value`) VALUES ('presupuesto anual');
INSERT INTO `keywords` (`value`) VALUES ('IFAI');
INSERT INTO `keywords` (`value`) VALUES ('solicitudes');
INSERT INTO `keywords` (`value`) VALUES ('tramites');
INSERT INTO `keywords` (`value`) VALUES ('pensión alimentaria');
INSERT INTO `keywords` (`value`) VALUES ('servidores públicos');
INSERT INTO `keywords` (`value`) VALUES ('estaciones migratorias');
INSERT INTO `keywords` (`value`) VALUES ('derechos humanos');
INSERT INTO `keywords` (`value`) VALUES ('SFP');
INSERT INTO `keywords` (`value`) VALUES ('violaciones');
INSERT INTO `keywords` (`value`) VALUES ('expediente');
INSERT INTO `keywords` (`value`) VALUES ('sanción');
INSERT INTO `keywords` (`value`) VALUES ('delito');
INSERT INTO `keywords` (`value`) VALUES ('FEVIMTRA');
INSERT INTO `keywords` (`value`) VALUES ('protección');
INSERT INTO `keywords` (`value`) VALUES ('procesos penales');
INSERT INTO `keywords` (`value`) VALUES ('programas sectoriales');
INSERT INTO `keywords` (`value`) VALUES ('SEDESOL');
INSERT INTO `keywords` (`value`) VALUES ('mujeres');
INSERT INTO `keywords` (`value`) VALUES ('giros negros');
INSERT INTO `keywords` (`value`) VALUES ('INMUJERES');
INSERT INTO `keywords` (`value`) VALUES ('Mesa Interinstitucional de Género y Migración');
INSERT INTO `keywords` (`value`) VALUES ('estadísticas');
INSERT INTO `keywords` (`value`) VALUES ('detenidos');
INSERT INTO `keywords` (`value`) VALUES ('SEGOB');
INSERT INTO `keywords` (`value`) VALUES ('OASISS');
INSERT INTO `keywords` (`value`) VALUES ('redes de trata');
INSERT INTO `keywords` (`value`) VALUES ('cuestionario');
INSERT INTO `keywords` (`value`) VALUES ('Lineamientos');
INSERT INTO `keywords` (`value`) VALUES ('entrevistas');
INSERT INTO `keywords` (`value`) VALUES ('SEDENA');
INSERT INTO `keywords` (`value`) VALUES ('minoría de edad');
INSERT INTO `keywords` (`value`) VALUES ('agentes migratorios');
INSERT INTO `keywords` (`value`) VALUES ('SEMARNAT');
INSERT INTO `keywords` (`value`) VALUES ('recomendaciones');
INSERT INTO `keywords` (`value`) VALUES ('CNDH');
INSERT INTO `keywords` (`value`) VALUES ('delegación migratoria');
INSERT INTO `keywords` (`value`) VALUES ('resolución');
INSERT INTO `keywords` (`value`) VALUES ('alojados');
INSERT INTO `keywords` (`value`) VALUES ('quejas');
INSERT INTO `keywords` (`value`) VALUES ('normas');
INSERT INTO `keywords` (`value`) VALUES ('vehículos oficiales');
INSERT INTO `keywords` (`value`) VALUES ('Red Nacional de Atención a Víctimas');
INSERT INTO `keywords` (`value`) VALUES ('alimentación');
INSERT INTO `keywords` (`value`) VALUES ('medicamentos');
INSERT INTO `keywords` (`value`) VALUES ('repatriados');
INSERT INTO `keywords` (`value`) VALUES ('gráficos');
INSERT INTO `keywords` (`value`) VALUES ('formatos');
INSERT INTO `keywords` (`value`) VALUES ('procedimiento');
INSERT INTO `keywords` (`value`) VALUES ('atención psicológica');
INSERT INTO `keywords` (`value`) VALUES ('refugio');
INSERT INTO `keywords` (`value`) VALUES ('estudios');
INSERT INTO `keywords` (`value`) VALUES ('infancia');
INSERT INTO `keywords` (`value`) VALUES ('acciones');
INSERT INTO `keywords` (`value`) VALUES ('capacitaciones');
INSERT INTO `keywords` (`value`) VALUES ('condiciones higiénicas');
INSERT INTO `keywords` (`value`) VALUES ('contratación');
INSERT INTO `keywords` (`value`) VALUES ('distribución geográfica');
INSERT INTO `keywords` (`value`) VALUES ('municipios');
INSERT INTO `keywords` (`value`) VALUES ('CISEN');
INSERT INTO `keywords` (`value`) VALUES ('SSP');
